<Project>
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net9.0</TargetFramework>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <TreatWarningsAsErrors Condition="'$(CI)' == 'true'">true</TreatWarningsAsErrors>

    <AnalysisLevel>9.0</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

    <InvariantGlobalization>false</InvariantGlobalization>
    <Deterministic>true</Deterministic>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>

    <NoWarn Condition="'$(CI)' != 'true'">$(NoWarn);NU1507</NoWarn>
    <RestoreNoWarn Condition="'$(CI)' != 'true'">$(RestoreNoWarn);NU1507</RestoreNoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
