<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageVersion Include="MediatR" Version="14.0.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.10.0" />
    <PackageVersion Include="Yarp.ReverseProxy" Version="2.3.0" />
    <PackageVersion Include="Confluent.Kafka" Version="2.12.0" />
    <PackageVersion Include="StackExchange.Redis" Version="2.10.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="FluentAssertions" Version="8.8.0" />
    <PackageVersion Include="Oracle.EntityFrameworkCore" Version="9.23.26300" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.18" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity" Version="2.3.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.18" />
  </ItemGroup>
</Project>